import { createContext, useContext, useState } from 'react';
import enUS from 'antd/locale/en_US';
import zhCN from 'antd/locale/zh_CN';
import viVN from 'antd/locale/vi_VN';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
import 'dayjs/locale/vi';

export const LANGS = [
  { value: 'en', label: 'EN' },
  { value: 'zh', label: '中文' },
  { value: 'vi', label: 'Tiếng Việt' },
];

export const ANTD_LOCALES = { en: enUS, zh: zhCN, vi: viVN };
const DAYJS_LOCALES = { en: 'en', zh: 'zh-cn', vi: 'vi' };

const DICT = {
  en: {
    'app.title': '🚗 Office Car Booking', 'app.carBooking': '🚗 Car Booking', 'app.driver': '🚗 Driver',
    'common.refresh': 'Refresh', 'common.back': 'Back', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.send': 'Send', 'common.logout': 'Logout', 'common.comingSoon': 'Coming soon', 'common.loading': 'Loading',
    'nav.book': 'Book', 'nav.bookFull': 'Book a Vehicle', 'nav.myBookings': 'My Bookings', 'nav.notifications': 'Notifications', 'nav.alerts': 'Alerts', 'nav.profile': 'Profile', 'nav.myTrips': 'My Trips', 'nav.manageBookings': 'Manage Bookings', 'nav.dashboard': 'Dashboard', 'nav.bookings': 'Bookings', 'nav.vehicles': 'Vehicles', 'nav.calendar': 'Calendar', 'nav.users': 'Users', 'nav.reports': 'Reports', 'nav.settings': 'Settings', 'nav.feedback': 'Feedback', 'nav.driver': 'Driver',
    'login.email': 'Email', 'login.password': 'Password', 'login.signIn': 'Sign in', 'login.setForgot': 'Set / forgot password', 'login.requestHint': 'Enter your email to receive a one-time code. New here? This also registers you.', 'login.sendCode': 'Send code', 'login.backToSignIn': 'Back to sign in', 'login.resetHint': 'We sent a 6-digit code to {email}. (Dev: check the server console.) Enter it and choose a password.', 'login.code': '6-digit code', 'login.newPassword': 'New password', 'login.min8': 'At least 8 characters', 'login.setAndSignIn': 'Set password & sign in', 'login.wrongCreds': 'Wrong email or password.', 'login.codeSent': 'If the email is valid, a code was sent. (Dev: check the server console.)', 'login.invalidCode': 'Invalid or expired code.', 'login.error': 'Something went wrong.', 'login.register': 'Create account', 'login.forgot': 'Forgot password', 'login.registerHint': 'New here? Enter your work email to receive a one-time code and create your account.', 'login.forgotHint': 'Enter your email to receive a one-time code to reset your password.', 'login.emailExists': 'An account with this email already exists. Please sign in.', 'login.noAccount': 'No account found for this email. Please register.',
    'status.pending': 'Pending', 'status.approved': 'Approved', 'status.rejected': 'Rejected', 'status.completed': 'Completed', 'status.no_show': 'No show', 'status.cancelled': 'Cancelled', 'status.maintenance': 'Maintenance', 'status.active': 'Active', 'status.inactive': 'Inactive',
    'book.title': 'Book a Vehicle', 'book.stepCar': 'Car', 'book.stepDay': 'Day', 'book.stepSlot': 'Slot', 'book.stepDetails': 'Details', 'book.pickDay': 'pick a day', 'book.greenOpen': '(green = open)', 'book.change': 'Change', 'book.noVehicles': 'No vehicles', 'book.pickSlot': 'pick a slot', 'book.quickBook': 'Quick book', 'book.destination': 'Destination', 'book.purpose': 'Purpose', 'book.passengers': 'Passengers', 'book.contact': 'Contact number', 'book.requester': 'Requester name', 'book.department': 'Department', 'book.review': 'Review', 'book.submit': 'Submit booking', 'book.findCars': 'Find available cars', 'book.submitted': 'Booking {code} submitted — awaiting approval.', 'book.slotTaken': 'That slot was just taken. Pick another.', 'book.failed': 'Booking failed.', 'book.couldNotLoad': 'Could not load availability.',
    'book.modeSlot': 'By slot', 'book.modeFullDay': 'Full day', 'book.fullDay': 'Full day', 'book.fullDayHint': 'Full-day bookings need at least 2 days’ notice and admin approval.', 'book.contactRequired': 'Contact number is required.', 'book.fullDayTooSoon': 'Full-day bookings must be requested at least 2 days in advance.', 'book.fullDayBlocked': 'This vehicle is reserved for the whole day.', 'book.fullDayTaken': 'Full-day booked',
    'guide.titleEmployee': 'Passenger responsibilities', 'guide.titleDriver': 'Driver responsibilities', 'guide.titleAdmin': 'Admin responsibilities', 'guide.gotIt': 'Got it', 'guide.help': 'Guidelines',
    'my.title': 'My Bookings', 'my.tabAll': 'All', 'my.tabUpcoming': 'Upcoming', 'my.tabPast': 'Past', 'my.tabCancelled': 'Cancelled', 'my.groupByDay': 'Group by day', 'my.none': 'No bookings here', 'my.cancelConfirm': 'Cancel this booking?', 'my.cancelled': 'Booking cancelled.', 'my.cancelErr': 'Could not cancel (only pending bookings can be cancelled).', 'my.cancelBooking': 'Cancel booking', 'my.loadErr': 'Could not load your bookings.',
    'f.status': 'Status', 'f.date': 'Date', 'f.slot': 'Slot', 'f.vehicle': 'Vehicle', 'f.destination': 'Destination', 'f.purpose': 'Purpose', 'f.passengers': 'Passengers', 'f.phone': 'Phone', 'f.employee': 'Employee', 'f.department': 'Department',
    'driver.today': 'Today', 'driver.upcomingOther': 'Upcoming & other', 'driver.noToday': 'No trips today.', 'driver.noTrips': 'No trips assigned', 'driver.noPending': 'No pending trips', 'driver.filterPending': 'Pending', 'driver.filterAll': 'All', 'driver.groupDay': 'Group day', 'driver.confirm': 'Confirm', 'driver.deny': 'Deny', 'driver.markCompleted': 'Mark completed', 'driver.noShow': 'No-show', 'driver.availableOn': 'Available on the trip day ({date}).', 'driver.denyTitle': 'Deny trip', 'driver.denyHint': 'The employee and admins will be notified with your reason.', 'driver.reasonPh': 'Why are you denying? (e.g. vehicle issue, schedule clash)', 'driver.maintenance': 'Maintenance', 'driver.confirmed': 'confirmed', 'driver.actionErr': 'Action not allowed.', 'driver.loadErr': 'Could not load your trips.', 'driver.vehErr': 'Could not update vehicle.', 'driver.awaitingApproval': 'Awaiting admin approval.',
    'profile.title': 'Profile', 'profile.name': 'Name', 'profile.email': 'Email', 'profile.department': 'Department', 'profile.role': 'Role', 'profile.save': 'Save profile', 'profile.updated': 'Profile updated.', 'profile.updateErr': 'Could not update profile.', 'profile.changePassword': 'Change password', 'profile.newPassword': 'New password', 'profile.confirmPassword': 'Confirm password', 'profile.mismatch': 'Passwords do not match', 'profile.pwChanged': 'Password changed.', 'profile.pwErr': 'Could not change password.', 'profile.reenter': 'Re-enter password',
    'notif.title': 'Notifications', 'notif.markAllRead': 'Mark all read', 'notif.none': 'No notifications', 'notif.new': 'new', 'notif.viewAll': 'View all',
    'fb.button': 'Feedback', 'fb.title': 'Send feedback', 'fb.type': 'Type', 'fb.bug': '🐞 Bug', 'fb.idea': '💡 Idea / request', 'fb.question': '❓ Question', 'fb.other': 'Other', 'fb.message': 'Message', 'fb.thanks': 'Thanks for the feedback!', 'fb.err': 'Could not send feedback. Try again.', 'fb.placeholder': 'What happened, or what would you like to see?', 'fb.describe': 'Please describe it',
    'role.employee': 'Employee', 'role.driver': 'Driver', 'role.admin': 'Admin',
    'admin.colActive': 'Active', 'admin.colNoShows': 'No-shows (mo.)', 'admin.colBooking': 'Booking', 'admin.colActions': 'Actions', 'admin.colType': 'Type', 'admin.colPlate': 'Plate', 'admin.colSeats': 'Seats', 'admin.colTransmission': 'Trans.', 'admin.colParking': 'Parking', 'admin.colDriver': 'Driver', 'admin.colFrom': 'From', 'admin.colPage': 'Page',
    'admin.edit': 'Edit', 'admin.delete': 'Delete', 'admin.add': 'Add', 'admin.addUser': 'Add user', 'admin.editUser': 'Edit user', 'admin.addVehicle': 'Add vehicle', 'admin.editVehicle': 'Edit vehicle', 'admin.slots': 'Slots', 'admin.unblock': 'Unblock', 'admin.ok': 'OK', 'admin.deactivate': 'Deactivate', 'admin.approve': 'Approve', 'admin.reject': 'Reject', 'admin.complete': 'Complete', 'admin.close': 'Close',
    'admin.deleteUserConfirm': 'Delete this user?', 'admin.cannotUndo': 'This cannot be undone.', 'admin.deactivateConfirm': 'Deactivate this vehicle?',
    'admin.driverAccount': 'Driver account', 'admin.image': 'Image', 'admin.notes': 'Notes', 'admin.blockedUntil': 'Blocked → {date}',
    'admin.updated': 'Updated.', 'admin.conflict': 'Conflict.', 'admin.updateErr': 'Could not update.', 'admin.roleUpdated': 'Role updated.', 'admin.activated': 'Activated.', 'admin.deactivated': 'Deactivated.', 'admin.unblocked': 'Unblocked.',
    'admin.usersLoadErr': 'Could not load users.', 'admin.userAdded': 'User added.', 'admin.emailExists': 'Email already exists.', 'admin.userAddErr': 'Could not add user.', 'admin.userUpdated': 'User updated.', 'admin.userDeleted': 'User deleted.', 'admin.userDeleteErr': 'Could not delete user.',
    'admin.vehiclesLoadErr': 'Could not load vehicles.', 'admin.saved': 'Saved.', 'admin.vehicleSaveErr': 'Could not save the vehicle.', 'admin.vehicleDeactivated': 'Vehicle deactivated.', 'admin.vehicleDeactivateErr': 'Could not deactivate.',
    'admin.slotsTitle': 'Time slots', 'admin.slotStart': 'Start', 'admin.slotEnd': 'End', 'admin.slotAdd': 'Add slot', 'admin.slotRemoveConfirm': 'Remove this slot?', 'admin.slotsUsingDefaults': 'This driver uses the default slots. Add a slot below to switch to a custom schedule.', 'admin.slotsEmpty': 'No custom slots — defaults apply.', 'admin.slotsLoadErr': 'Could not load slots.', 'admin.slotUpdateErr': 'Could not update slot.', 'admin.slotRemoved': 'Slot removed.', 'admin.slotRemoveErr': 'Could not remove slot.', 'admin.slotPickTimes': 'Pick a start and end time.', 'admin.slotAdded': 'Slot added.', 'admin.slotAddErr': 'Could not add slot.',
    'admin.bookingsLoadErr': 'Could not load bookings.', 'admin.bookingUpdated': 'Booking #{id} {status}.', 'admin.actionNotAllowed': 'Action not allowed for this booking.', 'admin.conflictsLoadErr': 'Could not load conflicts.', 'admin.typeSlot': 'Slot', 'admin.tabNeedsAction': 'Needs action', 'admin.tabNext2': 'Next 2 days', 'admin.filterStatus': 'Filter status', 'admin.approveFullDay': 'Approve full-day booking', 'admin.approveFullDayOk': 'Approve full-day', 'admin.fullDayAlertMsg': 'A full-day booking reserves the vehicle for the whole day.', 'admin.fullDayAlertDesc': 'Contact and reject any conflicting bookings below before approving. After approval, new bookings on this vehicle that day are blocked.', 'admin.noConflicts': 'No conflicting bookings that day.',
    'admin.dashboardLoadErr': 'Could not load the dashboard.', 'admin.nDays': '{n} days', 'admin.lastNDays': 'Last {n} days', 'admin.bySlot': 'By slot', 'admin.kpiActiveEmployees': 'Active employees', 'admin.kpiAvgPerEmployee': 'Avg bookings / employee', 'admin.kpiFullDayPending': 'Full-day pending', 'admin.needsApproval': 'Needs approval', 'admin.kpiTotalBookings': 'Total bookings', 'admin.bookingTrend': 'Booking trend (last {n} days)', 'admin.bookingsByStatus': 'Bookings by status', 'admin.noData': 'No data', 'admin.peakHours': 'Peak booking hours', 'admin.fullDayVsSlot': 'Full-day vs slot',
    'admin.previewErr': 'Could not load preview.', 'admin.exportErr': 'Export failed.', 'admin.report.bookings': 'Booking summary', 'admin.report.pending': 'Pending approvals', 'admin.report.utilisation': 'Utilisation', 'admin.report.monthly': 'Monthly', 'admin.exportExcel': 'Export to Excel', 'admin.previewCount': '{n} rows',
    'admin.feedbackLoadErr': 'Could not load feedback.', 'admin.fbCat.bug': 'Bug', 'admin.fbCat.idea': 'Idea', 'admin.fbCat.question': 'Question', 'admin.fbCat.other': 'Other', 'admin.fbStatus.new': 'New', 'admin.fbStatus.triaged': 'Triaged', 'admin.fbStatus.done': 'Done', 'admin.fbStatus.wontfix': "Won't fix",
    'admin.setBookingWeeks': 'Booking window (weeks shown to employees)', 'admin.setBookingsPerWeek': 'Max bookings per user per week', 'admin.setNoshowLimit': 'No-shows before a ban', 'admin.setBanMonths': 'Ban length (months)', 'admin.settingsLoadErr': 'Could not load settings.', 'admin.settingsSaved': 'Settings saved.', 'admin.settingsSaveErr': 'Could not save.', 'admin.saveSettings': 'Save settings',
    'admin.calendarLoadErr': 'Could not load the calendar.', 'admin.calendarDayErr': 'Could not load that day.', 'admin.legendAvailable': 'Available', 'admin.legendBooked': 'Booked', 'admin.legendFull': 'Full', 'admin.cellBookedLeft': '{booked} booked · {left} left', 'admin.timeline': 'Timeline', 'admin.timelineSoon': 'Timeline view — coming soon', 'admin.noBookings': 'No bookings',
  },
  zh: {
    'app.title': '🚗 公司用车预订', 'app.carBooking': '🚗 用车预订', 'app.driver': '🚗 司机',
    'common.refresh': '刷新', 'common.back': '返回', 'common.cancel': '取消', 'common.save': '保存', 'common.send': '发送', 'common.logout': '退出', 'common.comingSoon': '即将推出', 'common.loading': '加载中',
    'nav.book': '预订', 'nav.bookFull': '预订车辆', 'nav.myBookings': '我的预订', 'nav.notifications': '通知', 'nav.alerts': '通知', 'nav.profile': '个人资料', 'nav.myTrips': '我的行程', 'nav.manageBookings': '预订管理', 'nav.dashboard': '仪表盘', 'nav.bookings': '预订', 'nav.vehicles': '车辆', 'nav.calendar': '日历', 'nav.users': '用户', 'nav.reports': '报表', 'nav.settings': '设置', 'nav.feedback': '反馈', 'nav.driver': '司机',
    'login.email': '邮箱', 'login.password': '密码', 'login.signIn': '登录', 'login.setForgot': '设置 / 忘记密码', 'login.requestHint': '输入邮箱以获取一次性验证码。新用户将自动注册。', 'login.sendCode': '发送验证码', 'login.backToSignIn': '返回登录', 'login.resetHint': '已向 {email} 发送 6 位验证码。（开发环境：请查看服务器控制台。）请输入并设置密码。', 'login.code': '6 位验证码', 'login.newPassword': '新密码', 'login.min8': '至少 8 位', 'login.setAndSignIn': '设置密码并登录', 'login.wrongCreds': '邮箱或密码错误。', 'login.codeSent': '若邮箱有效，验证码已发送。（开发环境：请查看服务器控制台。）', 'login.invalidCode': '验证码无效或已过期。', 'login.error': '出错了。', 'login.register': '注册账号', 'login.forgot': '忘记密码', 'login.registerHint': '首次使用？输入工作邮箱以获取一次性验证码并创建账号。', 'login.forgotHint': '输入邮箱以获取一次性验证码来重置密码。', 'login.emailExists': '该邮箱已注册账号，请直接登录。', 'login.noAccount': '未找到该邮箱的账号，请先注册。',
    'status.pending': '待处理', 'status.approved': '已批准', 'status.rejected': '已拒绝', 'status.completed': '已完成', 'status.no_show': '未到', 'status.cancelled': '已取消', 'status.maintenance': '维护', 'status.active': '可用', 'status.inactive': '停用',
    'book.title': '预订车辆', 'book.stepCar': '车辆', 'book.stepDay': '日期', 'book.stepSlot': '时段', 'book.stepDetails': '详情', 'book.pickDay': '选择日期', 'book.greenOpen': '（绿色 = 可订）', 'book.change': '更改', 'book.noVehicles': '暂无车辆', 'book.pickSlot': '选择时段', 'book.quickBook': '快速预订', 'book.destination': '目的地', 'book.purpose': '事由', 'book.passengers': '乘客数', 'book.contact': '联系电话', 'book.requester': '申请人', 'book.department': '部门', 'book.review': '确认', 'book.submit': '提交预订', 'book.findCars': '查找可用车辆', 'book.submitted': '预订 {code} 已提交，等待确认。', 'book.slotTaken': '该时段刚被预订，请另选。', 'book.failed': '预订失败。', 'book.couldNotLoad': '无法加载可用情况。',
    'book.modeSlot': '按时段', 'book.modeFullDay': '全天', 'book.fullDay': '全天', 'book.fullDayHint': '全天预订需至少提前 2 天，并须管理员批准。', 'book.contactRequired': '请填写联系电话。', 'book.fullDayTooSoon': '全天预订须至少提前 2 天提交。', 'book.fullDayBlocked': '该车辆当天已被整日预订。', 'book.fullDayTaken': '已整日预订',
    'guide.titleEmployee': '乘客须知', 'guide.titleDriver': '司机须知', 'guide.titleAdmin': '管理员职责', 'guide.gotIt': '我知道了', 'guide.help': '使用须知',
    'my.title': '我的预订', 'my.tabAll': '全部', 'my.tabUpcoming': '即将', 'my.tabPast': '已过', 'my.tabCancelled': '已取消', 'my.groupByDay': '按天分组', 'my.none': '暂无预订', 'my.cancelConfirm': '取消该预订？', 'my.cancelled': '预订已取消。', 'my.cancelErr': '无法取消（仅可取消待处理预订）。', 'my.cancelBooking': '取消预订', 'my.loadErr': '无法加载您的预订。',
    'f.status': '状态', 'f.date': '日期', 'f.slot': '时段', 'f.vehicle': '车辆', 'f.destination': '目的地', 'f.purpose': '事由', 'f.passengers': '乘客数', 'f.phone': '电话', 'f.employee': '员工', 'f.department': '部门',
    'driver.today': '今天', 'driver.upcomingOther': '即将及其他', 'driver.noToday': '今天没有行程。', 'driver.noTrips': '暂无分配行程', 'driver.noPending': '没有待处理行程', 'driver.filterPending': '待处理', 'driver.filterAll': '全部', 'driver.groupDay': '按天', 'driver.confirm': '确认', 'driver.deny': '拒绝', 'driver.markCompleted': '标记完成', 'driver.noShow': '未到', 'driver.availableOn': '行程当天可操作（{date}）。', 'driver.denyTitle': '拒绝行程', 'driver.denyHint': '员工和管理员将收到您的理由。', 'driver.reasonPh': '拒绝原因？（如车辆故障、时间冲突）', 'driver.maintenance': '维护', 'driver.confirmed': '已确认', 'driver.actionErr': '操作不被允许。', 'driver.loadErr': '无法加载您的行程。', 'driver.vehErr': '无法更新车辆。', 'driver.awaitingApproval': '等待管理员批准。',
    'profile.title': '个人资料', 'profile.name': '姓名', 'profile.email': '邮箱', 'profile.department': '部门', 'profile.role': '角色', 'profile.save': '保存资料', 'profile.updated': '资料已更新。', 'profile.updateErr': '无法更新资料。', 'profile.changePassword': '修改密码', 'profile.newPassword': '新密码', 'profile.confirmPassword': '确认密码', 'profile.mismatch': '两次密码不一致', 'profile.pwChanged': '密码已修改。', 'profile.pwErr': '无法修改密码。', 'profile.reenter': '再次输入密码',
    'notif.title': '通知', 'notif.markAllRead': '全部标为已读', 'notif.none': '暂无通知', 'notif.new': '新', 'notif.viewAll': '查看全部',
    'fb.button': '反馈', 'fb.title': '发送反馈', 'fb.type': '类型', 'fb.bug': '🐞 缺陷', 'fb.idea': '💡 建议 / 需求', 'fb.question': '❓ 问题', 'fb.other': '其他', 'fb.message': '内容', 'fb.thanks': '感谢您的反馈！', 'fb.err': '发送失败，请重试。', 'fb.placeholder': '发生了什么，或您希望看到什么？', 'fb.describe': '请描述',
    'role.employee': '员工', 'role.driver': '司机', 'role.admin': '管理员',
    'admin.colActive': '启用', 'admin.colNoShows': '本月未到', 'admin.colBooking': '预订', 'admin.colActions': '操作', 'admin.colType': '类型', 'admin.colPlate': '车牌', 'admin.colSeats': '座位', 'admin.colTransmission': '变速', 'admin.colParking': '停车', 'admin.colDriver': '司机', 'admin.colFrom': '来自', 'admin.colPage': '页面',
    'admin.edit': '编辑', 'admin.delete': '删除', 'admin.add': '添加', 'admin.addUser': '添加用户', 'admin.editUser': '编辑用户', 'admin.addVehicle': '添加车辆', 'admin.editVehicle': '编辑车辆', 'admin.slots': '时段', 'admin.unblock': '解除', 'admin.ok': '正常', 'admin.deactivate': '停用', 'admin.approve': '批准', 'admin.reject': '拒绝', 'admin.complete': '完成', 'admin.close': '关闭',
    'admin.deleteUserConfirm': '删除该用户？', 'admin.cannotUndo': '此操作无法撤销。', 'admin.deactivateConfirm': '停用该车辆？',
    'admin.driverAccount': '司机账号', 'admin.image': '图片', 'admin.notes': '备注', 'admin.blockedUntil': '已封禁 → {date}',
    'admin.updated': '已更新。', 'admin.conflict': '冲突。', 'admin.updateErr': '无法更新。', 'admin.roleUpdated': '角色已更新。', 'admin.activated': '已启用。', 'admin.deactivated': '已停用。', 'admin.unblocked': '已解除。',
    'admin.usersLoadErr': '无法加载用户。', 'admin.userAdded': '用户已添加。', 'admin.emailExists': '邮箱已存在。', 'admin.userAddErr': '无法添加用户。', 'admin.userUpdated': '用户已更新。', 'admin.userDeleted': '用户已删除。', 'admin.userDeleteErr': '无法删除用户。',
    'admin.vehiclesLoadErr': '无法加载车辆。', 'admin.saved': '已保存。', 'admin.vehicleSaveErr': '无法保存车辆。', 'admin.vehicleDeactivated': '车辆已停用。', 'admin.vehicleDeactivateErr': '无法停用。',
    'admin.slotsTitle': '时段', 'admin.slotStart': '开始', 'admin.slotEnd': '结束', 'admin.slotAdd': '添加时段', 'admin.slotRemoveConfirm': '删除该时段？', 'admin.slotsUsingDefaults': '该司机使用默认时段。在下方添加时段即可切换为自定义。', 'admin.slotsEmpty': '无自定义时段 — 使用默认。', 'admin.slotsLoadErr': '无法加载时段。', 'admin.slotUpdateErr': '无法更新时段。', 'admin.slotRemoved': '时段已删除。', 'admin.slotRemoveErr': '无法删除时段。', 'admin.slotPickTimes': '请选择开始和结束时间。', 'admin.slotAdded': '时段已添加。', 'admin.slotAddErr': '无法添加时段。',
    'admin.bookingsLoadErr': '无法加载预订。', 'admin.bookingUpdated': '预订 #{id} {status}。', 'admin.actionNotAllowed': '该预订不允许此操作。', 'admin.conflictsLoadErr': '无法加载冲突。', 'admin.typeSlot': '时段', 'admin.tabNeedsAction': '待处理', 'admin.tabNext2': '近 2 天', 'admin.filterStatus': '筛选状态', 'admin.approveFullDay': '批准全天预订', 'admin.approveFullDayOk': '批准全天', 'admin.fullDayAlertMsg': '全天预订将占用该车辆一整天。', 'admin.fullDayAlertDesc': '批准前请联系并拒绝下方冲突的预订。批准后，当天该车辆的新预订将被阻止。', 'admin.noConflicts': '当天没有冲突的预订。',
    'admin.dashboardLoadErr': '无法加载仪表盘。', 'admin.nDays': '{n} 天', 'admin.lastNDays': '近 {n} 天', 'admin.bySlot': '按时段', 'admin.kpiActiveEmployees': '活跃员工', 'admin.kpiAvgPerEmployee': '人均预订', 'admin.kpiFullDayPending': '全天待批', 'admin.needsApproval': '待批准', 'admin.kpiTotalBookings': '预订总数', 'admin.bookingTrend': '预订趋势（近 {n} 天）', 'admin.bookingsByStatus': '按状态预订', 'admin.noData': '暂无数据', 'admin.peakHours': '高峰时段', 'admin.fullDayVsSlot': '全天 vs 时段',
    'admin.previewErr': '无法加载预览。', 'admin.exportErr': '导出失败。', 'admin.report.bookings': '预订汇总', 'admin.report.pending': '待批准', 'admin.report.utilisation': '使用率', 'admin.report.monthly': '月度', 'admin.exportExcel': '导出 Excel', 'admin.previewCount': '{n} 行',
    'admin.feedbackLoadErr': '无法加载反馈。', 'admin.fbCat.bug': '缺陷', 'admin.fbCat.idea': '建议', 'admin.fbCat.question': '问题', 'admin.fbCat.other': '其他', 'admin.fbStatus.new': '新', 'admin.fbStatus.triaged': '已分类', 'admin.fbStatus.done': '已完成', 'admin.fbStatus.wontfix': '不修复',
    'admin.setBookingWeeks': '预订窗口（向员工显示的周数）', 'admin.setBookingsPerWeek': '每位用户每周最多预订', 'admin.setNoshowLimit': '封禁前的未到次数', 'admin.setBanMonths': '封禁时长（月）', 'admin.settingsLoadErr': '无法加载设置。', 'admin.settingsSaved': '设置已保存。', 'admin.settingsSaveErr': '无法保存。', 'admin.saveSettings': '保存设置',
    'admin.calendarLoadErr': '无法加载日历。', 'admin.calendarDayErr': '无法加载当天。', 'admin.legendAvailable': '可用', 'admin.legendBooked': '已订', 'admin.legendFull': '已满', 'admin.cellBookedLeft': '已订 {booked} · 剩 {left}', 'admin.timeline': '时间线', 'admin.timelineSoon': '时间线视图 — 即将推出', 'admin.noBookings': '暂无预订',
  },
  vi: {
    'app.title': '🚗 Đặt xe văn phòng', 'app.carBooking': '🚗 Đặt xe', 'app.driver': '🚗 Tài xế',
    'common.refresh': 'Làm mới', 'common.back': 'Quay lại', 'common.cancel': 'Hủy', 'common.save': 'Lưu', 'common.send': 'Gửi', 'common.logout': 'Đăng xuất', 'common.comingSoon': 'Sắp ra mắt', 'common.loading': 'Đang tải',
    'nav.book': 'Đặt xe', 'nav.bookFull': 'Đặt xe', 'nav.myBookings': 'Đặt xe của tôi', 'nav.notifications': 'Thông báo', 'nav.alerts': 'Thông báo', 'nav.profile': 'Hồ sơ', 'nav.myTrips': 'Chuyến của tôi', 'nav.manageBookings': 'Quản lý đặt xe', 'nav.dashboard': 'Bảng điều khiển', 'nav.bookings': 'Đặt xe', 'nav.vehicles': 'Phương tiện', 'nav.calendar': 'Lịch', 'nav.users': 'Người dùng', 'nav.reports': 'Báo cáo', 'nav.settings': 'Cài đặt', 'nav.feedback': 'Phản hồi', 'nav.driver': 'Tài xế',
    'login.email': 'Email', 'login.password': 'Mật khẩu', 'login.signIn': 'Đăng nhập', 'login.setForgot': 'Đặt / quên mật khẩu', 'login.requestHint': 'Nhập email để nhận mã OTP. Người dùng mới sẽ được đăng ký.', 'login.sendCode': 'Gửi mã', 'login.backToSignIn': 'Quay lại đăng nhập', 'login.resetHint': 'Mã 6 số đã gửi tới {email}. (Dev: xem console máy chủ.) Nhập mã và chọn mật khẩu.', 'login.code': 'Mã 6 số', 'login.newPassword': 'Mật khẩu mới', 'login.min8': 'Ít nhất 8 ký tự', 'login.setAndSignIn': 'Đặt mật khẩu & đăng nhập', 'login.wrongCreds': 'Sai email hoặc mật khẩu.', 'login.codeSent': 'Nếu email hợp lệ, mã đã được gửi. (Dev: xem console máy chủ.)', 'login.invalidCode': 'Mã không hợp lệ hoặc đã hết hạn.', 'login.error': 'Đã có lỗi xảy ra.', 'login.register': 'Tạo tài khoản', 'login.forgot': 'Quên mật khẩu', 'login.registerHint': 'Lần đầu? Nhập email công ty để nhận mã một lần và tạo tài khoản.', 'login.forgotHint': 'Nhập email để nhận mã một lần đặt lại mật khẩu.', 'login.emailExists': 'Email này đã có tài khoản. Vui lòng đăng nhập.', 'login.noAccount': 'Không tìm thấy tài khoản cho email này. Vui lòng đăng ký.',
    'status.pending': 'Chờ duyệt', 'status.approved': 'Đã duyệt', 'status.rejected': 'Bị từ chối', 'status.completed': 'Hoàn thành', 'status.no_show': 'Không đến', 'status.cancelled': 'Đã hủy', 'status.maintenance': 'Bảo trì', 'status.active': 'Hoạt động', 'status.inactive': 'Ngừng',
    'book.title': 'Đặt xe', 'book.stepCar': 'Xe', 'book.stepDay': 'Ngày', 'book.stepSlot': 'Khung giờ', 'book.stepDetails': 'Chi tiết', 'book.pickDay': 'chọn ngày', 'book.greenOpen': '(xanh = còn chỗ)', 'book.change': 'Đổi', 'book.noVehicles': 'Không có xe', 'book.pickSlot': 'chọn khung giờ', 'book.quickBook': 'Đặt nhanh', 'book.destination': 'Điểm đến', 'book.purpose': 'Mục đích', 'book.passengers': 'Số khách', 'book.contact': 'Số liên hệ', 'book.requester': 'Người yêu cầu', 'book.department': 'Phòng ban', 'book.review': 'Xem lại', 'book.submit': 'Gửi đặt xe', 'book.findCars': 'Tìm xe trống', 'book.submitted': 'Đã gửi đặt xe {code} — chờ duyệt.', 'book.slotTaken': 'Khung giờ vừa bị đặt. Chọn khung khác.', 'book.failed': 'Đặt xe thất bại.', 'book.couldNotLoad': 'Không tải được tình trạng xe.',
    'book.modeSlot': 'Theo khung giờ', 'book.modeFullDay': 'Cả ngày', 'book.fullDay': 'Cả ngày', 'book.fullDayHint': 'Đặt cả ngày cần báo trước ít nhất 2 ngày và phải được quản trị viên duyệt.', 'book.contactRequired': 'Vui lòng nhập số liên hệ.', 'book.fullDayTooSoon': 'Đặt cả ngày phải được gửi trước ít nhất 2 ngày.', 'book.fullDayBlocked': 'Xe này đã được đặt trọn ngày.', 'book.fullDayTaken': 'Đã đặt cả ngày',
    'guide.titleEmployee': 'Trách nhiệm của hành khách', 'guide.titleDriver': 'Trách nhiệm của tài xế', 'guide.titleAdmin': 'Trách nhiệm của quản trị viên', 'guide.gotIt': 'Đã hiểu', 'guide.help': 'Hướng dẫn',
    'my.title': 'Đặt xe của tôi', 'my.tabAll': 'Tất cả', 'my.tabUpcoming': 'Sắp tới', 'my.tabPast': 'Đã qua', 'my.tabCancelled': 'Đã hủy', 'my.groupByDay': 'Nhóm theo ngày', 'my.none': 'Không có đặt xe', 'my.cancelConfirm': 'Hủy đặt xe này?', 'my.cancelled': 'Đã hủy đặt xe.', 'my.cancelErr': 'Không thể hủy (chỉ hủy được đơn chờ duyệt).', 'my.cancelBooking': 'Hủy đặt xe', 'my.loadErr': 'Không tải được đặt xe của bạn.',
    'f.status': 'Trạng thái', 'f.date': 'Ngày', 'f.slot': 'Khung giờ', 'f.vehicle': 'Xe', 'f.destination': 'Điểm đến', 'f.purpose': 'Mục đích', 'f.passengers': 'Số khách', 'f.phone': 'Điện thoại', 'f.employee': 'Nhân viên', 'f.department': 'Phòng ban',
    'driver.today': 'Hôm nay', 'driver.upcomingOther': 'Sắp tới & khác', 'driver.noToday': 'Không có chuyến hôm nay.', 'driver.noTrips': 'Chưa có chuyến nào', 'driver.noPending': 'Không có chuyến chờ', 'driver.filterPending': 'Chờ', 'driver.filterAll': 'Tất cả', 'driver.groupDay': 'Theo ngày', 'driver.confirm': 'Xác nhận', 'driver.deny': 'Từ chối', 'driver.markCompleted': 'Hoàn thành', 'driver.noShow': 'Không đến', 'driver.availableOn': 'Khả dụng vào ngày chuyến ({date}).', 'driver.denyTitle': 'Từ chối chuyến', 'driver.denyHint': 'Nhân viên và quản trị viên sẽ nhận được lý do.', 'driver.reasonPh': 'Lý do từ chối? (vd: xe hỏng, trùng lịch)', 'driver.maintenance': 'Bảo trì', 'driver.confirmed': 'đã xác nhận', 'driver.actionErr': 'Thao tác không được phép.', 'driver.loadErr': 'Không tải được chuyến của bạn.', 'driver.vehErr': 'Không cập nhật được xe.', 'driver.awaitingApproval': 'Đang chờ quản trị viên duyệt.',
    'profile.title': 'Hồ sơ', 'profile.name': 'Tên', 'profile.email': 'Email', 'profile.department': 'Phòng ban', 'profile.role': 'Vai trò', 'profile.save': 'Lưu hồ sơ', 'profile.updated': 'Đã cập nhật hồ sơ.', 'profile.updateErr': 'Không cập nhật được hồ sơ.', 'profile.changePassword': 'Đổi mật khẩu', 'profile.newPassword': 'Mật khẩu mới', 'profile.confirmPassword': 'Xác nhận mật khẩu', 'profile.mismatch': 'Mật khẩu không khớp', 'profile.pwChanged': 'Đã đổi mật khẩu.', 'profile.pwErr': 'Không đổi được mật khẩu.', 'profile.reenter': 'Nhập lại mật khẩu',
    'notif.title': 'Thông báo', 'notif.markAllRead': 'Đánh dấu đã đọc', 'notif.none': 'Không có thông báo', 'notif.new': 'mới', 'notif.viewAll': 'Xem tất cả',
    'fb.button': 'Phản hồi', 'fb.title': 'Gửi phản hồi', 'fb.type': 'Loại', 'fb.bug': '🐞 Lỗi', 'fb.idea': '💡 Ý tưởng / đề xuất', 'fb.question': '❓ Câu hỏi', 'fb.other': 'Khác', 'fb.message': 'Nội dung', 'fb.thanks': 'Cảm ơn phản hồi của bạn!', 'fb.err': 'Không gửi được, thử lại.', 'fb.placeholder': 'Bạn gặp vấn đề gì, hoặc muốn thêm gì?', 'fb.describe': 'Vui lòng mô tả',
    'role.employee': 'Nhân viên', 'role.driver': 'Tài xế', 'role.admin': 'Quản trị',
    'admin.colActive': 'Hoạt động', 'admin.colNoShows': 'Vắng (tháng)', 'admin.colBooking': 'Đặt xe', 'admin.colActions': 'Thao tác', 'admin.colType': 'Loại', 'admin.colPlate': 'Biển số', 'admin.colSeats': 'Chỗ', 'admin.colTransmission': 'Hộp số', 'admin.colParking': 'Bãi đỗ', 'admin.colDriver': 'Tài xế', 'admin.colFrom': 'Từ', 'admin.colPage': 'Trang',
    'admin.edit': 'Sửa', 'admin.delete': 'Xóa', 'admin.add': 'Thêm', 'admin.addUser': 'Thêm người dùng', 'admin.editUser': 'Sửa người dùng', 'admin.addVehicle': 'Thêm xe', 'admin.editVehicle': 'Sửa xe', 'admin.slots': 'Khung giờ', 'admin.unblock': 'Bỏ chặn', 'admin.ok': 'OK', 'admin.deactivate': 'Ngừng', 'admin.approve': 'Duyệt', 'admin.reject': 'Từ chối', 'admin.complete': 'Hoàn thành', 'admin.close': 'Đóng',
    'admin.deleteUserConfirm': 'Xóa người dùng này?', 'admin.cannotUndo': 'Không thể hoàn tác.', 'admin.deactivateConfirm': 'Ngừng xe này?',
    'admin.driverAccount': 'Tài khoản tài xế', 'admin.image': 'Hình ảnh', 'admin.notes': 'Ghi chú', 'admin.blockedUntil': 'Bị chặn → {date}',
    'admin.updated': 'Đã cập nhật.', 'admin.conflict': 'Xung đột.', 'admin.updateErr': 'Không cập nhật được.', 'admin.roleUpdated': 'Đã cập nhật vai trò.', 'admin.activated': 'Đã kích hoạt.', 'admin.deactivated': 'Đã ngừng.', 'admin.unblocked': 'Đã bỏ chặn.',
    'admin.usersLoadErr': 'Không tải được người dùng.', 'admin.userAdded': 'Đã thêm người dùng.', 'admin.emailExists': 'Email đã tồn tại.', 'admin.userAddErr': 'Không thêm được người dùng.', 'admin.userUpdated': 'Đã cập nhật người dùng.', 'admin.userDeleted': 'Đã xóa người dùng.', 'admin.userDeleteErr': 'Không xóa được người dùng.',
    'admin.vehiclesLoadErr': 'Không tải được xe.', 'admin.saved': 'Đã lưu.', 'admin.vehicleSaveErr': 'Không lưu được xe.', 'admin.vehicleDeactivated': 'Đã ngừng xe.', 'admin.vehicleDeactivateErr': 'Không ngừng được.',
    'admin.slotsTitle': 'Khung giờ', 'admin.slotStart': 'Bắt đầu', 'admin.slotEnd': 'Kết thúc', 'admin.slotAdd': 'Thêm khung giờ', 'admin.slotRemoveConfirm': 'Xóa khung giờ này?', 'admin.slotsUsingDefaults': 'Tài xế này dùng khung giờ mặc định. Thêm khung giờ bên dưới để chuyển sang lịch tùy chỉnh.', 'admin.slotsEmpty': 'Không có khung giờ tùy chỉnh — dùng mặc định.', 'admin.slotsLoadErr': 'Không tải được khung giờ.', 'admin.slotUpdateErr': 'Không cập nhật được khung giờ.', 'admin.slotRemoved': 'Đã xóa khung giờ.', 'admin.slotRemoveErr': 'Không xóa được khung giờ.', 'admin.slotPickTimes': 'Chọn giờ bắt đầu và kết thúc.', 'admin.slotAdded': 'Đã thêm khung giờ.', 'admin.slotAddErr': 'Không thêm được khung giờ.',
    'admin.bookingsLoadErr': 'Không tải được đặt xe.', 'admin.bookingUpdated': 'Đặt xe #{id} {status}.', 'admin.actionNotAllowed': 'Không được phép thao tác với đặt xe này.', 'admin.conflictsLoadErr': 'Không tải được xung đột.', 'admin.typeSlot': 'Khung giờ', 'admin.tabNeedsAction': 'Cần xử lý', 'admin.tabNext2': '2 ngày tới', 'admin.filterStatus': 'Lọc trạng thái', 'admin.approveFullDay': 'Duyệt đặt cả ngày', 'admin.approveFullDayOk': 'Duyệt cả ngày', 'admin.fullDayAlertMsg': 'Đặt cả ngày giữ xe trọn ngày.', 'admin.fullDayAlertDesc': 'Hãy liên hệ và từ chối các đặt xe xung đột bên dưới trước khi duyệt. Sau khi duyệt, các đặt xe mới cho xe này trong ngày đó sẽ bị chặn.', 'admin.noConflicts': 'Không có đặt xe xung đột ngày đó.',
    'admin.dashboardLoadErr': 'Không tải được bảng điều khiển.', 'admin.nDays': '{n} ngày', 'admin.lastNDays': '{n} ngày qua', 'admin.bySlot': 'Theo khung giờ', 'admin.kpiActiveEmployees': 'Nhân viên hoạt động', 'admin.kpiAvgPerEmployee': 'TB đặt xe / nhân viên', 'admin.kpiFullDayPending': 'Cả ngày chờ duyệt', 'admin.needsApproval': 'Cần duyệt', 'admin.kpiTotalBookings': 'Tổng đặt xe', 'admin.bookingTrend': 'Xu hướng đặt xe ({n} ngày qua)', 'admin.bookingsByStatus': 'Đặt xe theo trạng thái', 'admin.noData': 'Không có dữ liệu', 'admin.peakHours': 'Giờ cao điểm', 'admin.fullDayVsSlot': 'Cả ngày vs khung giờ',
    'admin.previewErr': 'Không tải được xem trước.', 'admin.exportErr': 'Xuất thất bại.', 'admin.report.bookings': 'Tổng hợp đặt xe', 'admin.report.pending': 'Chờ duyệt', 'admin.report.utilisation': 'Mức sử dụng', 'admin.report.monthly': 'Hàng tháng', 'admin.exportExcel': 'Xuất Excel', 'admin.previewCount': '{n} dòng',
    'admin.feedbackLoadErr': 'Không tải được phản hồi.', 'admin.fbCat.bug': 'Lỗi', 'admin.fbCat.idea': 'Ý tưởng', 'admin.fbCat.question': 'Câu hỏi', 'admin.fbCat.other': 'Khác', 'admin.fbStatus.new': 'Mới', 'admin.fbStatus.triaged': 'Đã phân loại', 'admin.fbStatus.done': 'Xong', 'admin.fbStatus.wontfix': 'Không sửa',
    'admin.setBookingWeeks': 'Cửa sổ đặt xe (số tuần hiển thị cho nhân viên)', 'admin.setBookingsPerWeek': 'Số đặt xe tối đa mỗi tuần', 'admin.setNoshowLimit': 'Số lần vắng trước khi bị cấm', 'admin.setBanMonths': 'Thời gian cấm (tháng)', 'admin.settingsLoadErr': 'Không tải được cài đặt.', 'admin.settingsSaved': 'Đã lưu cài đặt.', 'admin.settingsSaveErr': 'Không lưu được.', 'admin.saveSettings': 'Lưu cài đặt',
    'admin.calendarLoadErr': 'Không tải được lịch.', 'admin.calendarDayErr': 'Không tải được ngày đó.', 'admin.legendAvailable': 'Còn trống', 'admin.legendBooked': 'Đã đặt', 'admin.legendFull': 'Đã đầy', 'admin.cellBookedLeft': 'Đã đặt {booked} · còn {left}', 'admin.timeline': 'Dòng thời gian', 'admin.timelineSoon': 'Dòng thời gian — sắp ra mắt', 'admin.noBookings': 'Không có đặt xe',
  },
};

function translate(lang, key, params) {
  let s = (DICT[lang] && DICT[lang][key]) ?? DICT.en[key] ?? key;
  if (params) for (const [k, v] of Object.entries(params)) s = s.replace(`{${k}}`, v);
  return s;
}

const LangContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('lang') || 'en');
  dayjs.locale(DAYJS_LOCALES[lang] || 'en');
  const setLang = (l) => {
    localStorage.setItem('lang', l);
    dayjs.locale(DAYJS_LOCALES[l] || 'en');
    setLangState(l);
  };
  const t = (key, params) => translate(lang, key, params);
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
